name: Deploy to Render

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build application
      run: npm run build
    
    - name: Deploy to Render
      run: |
        echo "Starting Render deployment..."
        
        if [ -z "${{ secrets.RENDER_DEPLOY_HOOK }}" ]; then
          echo "Error: RENDER_DEPLOY_HOOK is not set"
          exit 1
        fi
        
        echo "Triggering deployment..."
        RESPONSE=$(curl -s -w "\n%{http_code}" -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}")
        HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
        RESPONSE_BODY=$(echo "$RESPONSE" | sed '$d')
        
        echo "Response code: $HTTP_CODE"
        echo "Response body: $RESPONSE_BODY"
        
        if [ "$HTTP_CODE" -ge 200 ] && [ "$HTTP_CODE" -lt 300 ]; then
          echo "Deployment triggered successfully!"
        else
          echo "Error: Deployment trigger failed with status code $HTTP_CODE"
          echo "$RESPONSE_BODY"
          exit 1
        fi 